# Generated by Django 4.1.13 on 2025-03-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=100)),
                ("price", models.FloatField()),
                ("holding_cost", models.FloatField()),
                ("ordering_cost", models.FloatField()),
                ("quantity", models.IntegerField()),
                ("predicted_sales", models.FloatField(blank=True, null=True)),
                ("eoq", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
